site_name: ElentraJS Documentation
repo_url: https://github.com/EntradaProject/entrada-1x-docs/ejs
theme: readthedocs
pages:
- 'Home': 'index.md'
- 'Overview':
  - 'Introduction': 'manual/overview/Introduction.md'
  - 'Standards &amp; Principles': 'manual/overview/Standards-and-Principles.md'
  - 'Integrating with ME v1.x': 'manual/platform-integration/Integrating-with-Entrada-1.x-ME.md'
- 'Architecture':
  - 'Layers': 'manual/architecture/Architecture.md'
- 'Environments':
  - 'Configuration': 'manual/environments/Environment-Configuration.md'
  - 'Entry Points': 'manual/environments/Entry-Points.md'
- 'Bootstrapping':
  - 'Booting an EJS App': 'manual/Bootstrap.md'
- 'File Handling':
  - 'Unified File Handling': 'manual/file-handling/Unified-File-Handling.md'
  - 'Use Statement': 'manual/file-handling/Use-Statement.md'
- 'Modules':
  - 'Configuration': 'manual/modules/Modules.md'
  - 'Components': 'manual/modules/Components.md'
- 'Routing':
  - 'Overview': 'manual/routing/Routing.md'
  - 'Logical Controllers': 'manual/routing/Logical-Controllers.md'
  - 'Routes': 'manual/routing/Routes.md'
  - 'Route Collections': 'manual/routing/Route-Collections.md'
  - 'Path Matching': 'manual/routing/Path-Matching.md'
  - 'Path Generation': 'manual/routing/Path-Generation.md'
  - 'View Links': 'manual/routing/ViewLink.md'
- 'HTTP Library':
  - 'REST Client': 'manual/http/REST-Client.md'
  - 'HTTP Client': 'manual/http/HTTP-Client.md'