site_name: Entrada User Documentation
repo_url: https://github.com/EntradaProject/entrada-1x-docs
theme: readthedocs
pages:
- 'Home': 'index.md'
- 'About':
  - 'License': 'about/license.md'
  - 'Reporting Issues': 'about/reporting-issues.md'
- 'Support':
  - 'Overview': 'support/overview.md'
  - 'Knowledge Base': 'support/kb.md'
  - 'Feature Requests': 'support/featurerequests.md'
- 'System Setup':
  - 'Getting Started': 'systemsetup/index.md'
  - 'Organisation': 'systemsetup/organisation.md'
  - 'Location': 'systemsetup/location.md'
  - 'Departments': 'systemsetup/departments.md'
  - 'Event Types': 'systemsetup/eventtypes.md'
- 'Curriculum Management':
  - 'Getting Started': 'curriculum/index.md'
  - 'Curriculum Layout': 'curriculum/layout.md'
  - 'Curriculum Tracks': 'curriculum/tracks.md'
  - 'Curriculum Map Versions': 'curriculum/mapversions.md'
  - 'Curriculum Tags': 'curriculum/tags.md'
  - 'Context-Based Linkages': 'curriculum/contextbasedlinkages.md'
  - 'Hot Topics': 'curriculum/hottopics.md'
  - 'Curriculum Search': 'curriculum/search.md'
  - 'Curriculum Explorer': 'curriculum/explorer.md'
  - 'Curriculum Matrix': 'curriculum/matrix.md'
- 'User Management':
  - 'Getting Started with Users': 'users/index.md'
  - 'Create Users': 'users/create.md'
  - 'User Cohorts': 'users/cohorts.md'
  - 'User Permissions': 'users/permissions.md'
  - 'User Disclaimers': 'users/disclaimers.md'
  - 'User Metadata': 'users/metadata.md'
  - 'User Incidents': 'users/incidents.md'
  - 'User Profile Preferences': 'users/profilepreferences.md'
- 'Student Management':
  - 'Getting Started': 'studentmanagement/index.md'
  - 'Disciplinary Actions': 'studentmanagement/discipline.md'
  - 'Formal Remediation': 'studentmanagement/remediation.md'
  - 'Leaves of Absence': 'studentmanagement/leavesabsence.md'
  - 'MSPR': 'studentmanagement/mspr.md'
  - 'Observerships': 'studentmanagement/observerships.md'
- 'Communities':
  - 'Getting Started': 'communities/index.md'
  - 'Community Types and Uses': 'communities/types.md'
  - 'Creating a Community': 'communities/create.md'
  - 'Community Pages': 'communities/pages.md'
  - 'Manage Community': 'communities/manage.md'
  - 'Using Different Page Types': 'communities/pageactions.md'
  - 'Subscribing to Community Notifications': 'communities/subscribecnotifications.md'
- 'Courses':
  - 'Getting Started': 'courses/index.md'
  - 'Creating and Managing Courses': 'courses/create.md'
  - 'Course Content': 'courses/content.md'
  - 'Course Enrolment': 'courses/enrolment.md'
  - 'Course Website': 'courses/website.md'
  - 'Course Groups': 'courses/groups.md'
- 'Scheduling Events':
  - 'Getting Started': 'scheduling/index.md'
  - 'Creating and Managing a Schedule': 'scheduling/create.md'
  - 'Copying an Existing Schedule': 'scheduling/copy.md'
  - 'Recurring Events': 'scheduling/recurringevents.md'
  - 'Parent Child Tool': 'scheduling/parentchild.md'
  - 'Rotation Blocks': 'scheduling/rotationblocks.md'
- 'Event Pages':
  - 'Setup': 'eventpages/setup.md'
  - 'Content': 'eventpages/content.md'
  - 'Attendance': 'eventpages/attendance.md'
  - 'History': 'eventpages/history.md'
  - 'Statistics': 'eventpages/statistics.md'
  - 'Reports': 'eventpages/reports.md'
- 'Calendar':
  - 'Getting Started': 'calendar/index.md'
- 'Units':
  - 'Getting Started': 'units/index.md'
  - 'Creating Units': 'units/create.md'
  - 'Learner View': 'units/learnerview.md'
- 'Clinical Learning':
  - Getting Started: 'clinicallearning/index.md'
  - Logbook: 'clinicallearning/logbook.md'
  - Lottery: 'clinicallearning/lottery.md'
  - Rotations: 'clinicallearning/rotations.md'
  - Electives: 'clinicallearning/electives.md'
- 'Assessment and Evaluation':
  - 'Getting Started': 'assessment-evaluation/index.md'
  - 'Settings': 'assessment-evaluation/settings.md'
  - 'Items': 'assessment-evaluation/items.md'
  - 'Forms': 'assessment-evaluation/forms.md'
  - 'Form Templates': 'assessment-evaluation/formtemplates.md'
  - 'Distributions': 'assessment-evaluation/distributions.md'
  - 'Faculty View': 'assessment-evaluation/facultyview.md'
  - 'Learner View': 'assessment-evaluation/learnerview.md'
  - 'Program Coordinator View': 'assessment-evaluation/pcoorview.md'
  - 'Reports in A&E': 'assessment-evaluation/reports.md'
- 'Exams':
  - 'Getting Started': 'exams/index.md'
  - 'Create Exam Items': 'exams/items.md'
  - 'Importing Exam Items': 'exams/imports.md'
  - 'Create an Exam': 'exams/create.md'
  - 'Post an Exam': 'exams/post.md'
  - 'Reporting Exams Results': 'exams/reporting.md'
- 'Gradebook':
  - 'Getting Started': 'gradebook/index.md'
  - 'Create Gradebook Assessments': 'gradebook/create.md'
  - 'Enterging Grades': 'gradebook/entergrades.md'
  - 'Create A Dropbox': 'gradebook/dropbox.md'
  - 'Reporting Gradebook Results': 'gradebook/reporting.md'
- 'Quizzes':
  - 'Getting Started': 'quizzes/index.md'
  - 'Creating and Managing Quizzes': 'quizzes/create.md'
- 'Notices':
  - 'Getting Started': 'notices/index.md'
  - 'Create and Manage Notices': 'notices/create.md'
  - 'User View of Notices': 'notices/userview.md'
- 'Polls':
  - 'Getting Started': 'polls/index.md'
- 'mspr':
  - 'Getting Started': 'mspr/index.md'
  - 'Managing the MSPR': 'mspr/manage.md'
  - 'Learner View of the MSPR': 'mspr/learnerview.md'
- 'eportfolio':
  - 'Getting Started': 'eportfolio/index.md'
  - 'Manage': 'eportfolio/manage.md'
  - 'Manage Advisors and Groups': 'eportfolio/manageadvisors.md'
  - 'Advisors': 'eportfolio/advisors.md'
  - 'Learners': 'eportfolio/learners.md'
  - 'Gradebook': 'eportfolio/gradebook.md'
- 'Annual Reports':
  - 'Getting Started': 'annualreports/index.md'
  - 'Faculty Annual Reports': 'annualreports/faculty.md'
  - 'Reporting Options': 'annualreports/reports.md'
- 'Regional Education':
  - 'Getting Started': 'regionaled/index.md'
  - 'Manage Regions': 'regionaled/regions.md'
  - 'Manage Apartments': 'regionaled/apartments.md'
  - 'Scheduling Learners': 'regionaled/schedules.md'
- 'User Tools':
  - 'Swithcing Organisations': 'usertools/switchorganisations.md'
  - 'Display Style': 'usertools/displaystyle.md'
  - 'My Bookmarks': 'usertools/bookmark.md'
  - 'People Search': 'usertools/peoplesearch.md'
  - 'Masking Identity': 'usertools/maskingid.md'
  - 'RSS Feeds': 'usertools/rssfeeds.md'
  - 'Subscribing to Calendars': 'usertools/subscribecalendar.md'
  - 'Give Feedback': 'usertools/feedback.md'
- 'System Reports':
  - 'Getting Started with System Reports': 'systemreports/index.md'
  - 'Curriculum Reports': 'systemreports/curriculum.md'
  - 'Teaching Event Reports': 'systemreports/teachingevent.md'
  - 'Learner Incident Reports': 'systemreports/learnerincident.md'
  - 'Usage Reports': 'systemreports/usage.md'
  - 'Assessment Reports': 'systemreports/assessment.md'
  - 'External Reporting': 'systemreports/external.md'
  - 'MSPR Reporting': 'systemreports/mspr.md'
- 'Rich Text Content':
  - 'Using Rich Text Content Editor': 'richtexteditor/index.md'
  - 'Embedding Media': 'richtexteditor/embedmedia.md'
