site_name: Entrada User Documentation
repo_url: https://github.com/EntradaProject/entrada-1x-docs
theme: readthedocs
pages:
- 'Home': 'index.md'
- 'About':
  - 'License': 'about/license.md'
  - 'Reporting Issues': 'about/reporting-issues.md'
- 'Support':
  - 'Overview': 'support/overview.md'
  - 'Knowledge Base': 'support/kb.md'
  - 'Feature Requests': 'support/featurerequests.md'
- 'System Setup':
  - 'Getting Started': 'systemsetup/index.md'
  - 'Organization': 'systemsetup/organization.md'
  - 'Location': 'systemsetup/location.md'
  - 'Departments': 'systemsetup/departments.md'
- 'Curriculum Management':
  - 'Getting Started': 'curriculum/index.md'
  - 'Curriculum Layout': 'curriculum/layout.md'
  - 'Curriculum Tracks': 'curriculum/tracks.md'
  - 'Curriculum Map Versions': 'curriculum/mapversions.md'
  - 'Curriculum Tags': 'curriculum/tags.md'
  - 'Hot Topics': 'curriculum/hottopics.md'
- 'User Management':
  - 'Create Users': 'users/create.md'
  - 'User Cohorts': 'users/cohorts.md'
  - 'User Permissions': 'users/permissions.md'
  - 'User Disclaimers': 'users/disclaimers.md'
  - 'User Metadata': 'users/metadata.md'
  - 'User Incidents': 'users/incidents.md'
  - 'User Profile Preferences': 'users/profilepreferences.md'
- 'Student Management':
  - 'Getting Started': 'studentmanagement/index.md'
  - 'Disciplinary Actions': 'studentmanagement/discipline.md'
  - 'Formal Remediation': 'studentmanagement/remediation.md'
  - 'Leaves of Absence': 'studentmanagement/leavesabsence.md'
  - 'MSPR': 'studentmanagement/mspr.md'
  - 'Observerships': 'studentmanagement/observerships.md'
- 'Communities':
  - 'Getting Started': 'communities/index.md'
  - 'Community Types and Uses': 'communities/types.md'
  - 'Creating a Community': 'communities/create.md'
  - 'Community Pages': 'communities/pages.md'
  - 'Manage Community': 'communities/manage.md'
  - 'What Users Can Do': 'communities/useractions.md'
- 'Courses':
  - 'Getting Started': 'courses/index.md'
  - 'Creating and Managing Courses': 'courses/create.md'
  - 'Course Content': 'courses/content.md'
  - 'Course Enrolment': 'courses/enrolment.md'
  - 'Course Website': 'courses/website.md'
  - 'Course Groups': 'courses/groups.md'
- 'Scheduling':
  - 'Getting Started': 'scheduling/index.md'
  - 'Creating and Managing a Schedule': 'scheduling/create.md'
  - 'Copying an Existing Schedule': 'scheduling/copy.md'
  - 'Recurring Events': 'scheduling/recurringevents.md'
- 'Calendar':
  - 'Getting Started': 'calendar/index.md'
- 'Units':
  - 'Getting Started': 'units/index.md'
  - 'Creating Units': 'units/create.md'
  - 'Learner View': 'units/learnerview.md'
- 'Clinical Learning':
  - Getting Started: 'clinicallearning/index.md'
  - Logbook: 'clinicallearning/logbook.md'
  - Lottery: 'clinicallearning/lottery.md'
  - Rotations: 'clinicallearning/rotations.md'
- 'Assessment and Evaluation':
  - 'Getting Started': 'assessment-evaluation/index.md'
  - 'Settings': 'assessment-evaluation/settings.md'
  - 'Items': 'assessment-evaluation/items.md'
  - 'Forms': 'assessment-evaluation/forms.md'
  - 'Distributions': 'assessment-evaluation/distributions.md'
- 'Exams':
  - 'Getting Started': 'exams/index.md'
  - 'Create Exam Items': 'exams/items.md'
  - 'Create an Exam': 'exams/create.md'
  - 'Post an Exam': 'exams/post.md'
  - 'Reporting Exams Results': 'exams/reporting.md'
- 'Gradebook':
  - 'Getting Started': 'gradebook/index.md'
  - 'Create Gradebook Assessments': 'gradebook/create.md'
  - 'Enterging Grades': 'gradebook/entergrades.md'
  - 'Create A Dropbox': 'gradebook/dropbox.md'
  - 'Reporting Gradebook Results': 'gradebook/reporting.md'
- 'Quizzes':
  - 'Getting Started': 'quizzes/index.md'
  - 'Creating and Managing Quizzes': 'quizzes/create.md'
- 'Notices':
  - 'Getting Started': 'notices/index.md'
  - 'Create and Manage Notices': 'notices/create.md'
  - 'User View of Notices': 'notices/userview.md'
- 'Polls':
  - 'Getting Started': 'polls/index.md'
- 'mspr':
  - 'Getting Started': 'mspr/index.md'
  - 'MSPR Options': 'mspr/options.md'
- 'eportfolio':
  - 'Getting Started': 'eportfolio/index.md'
  - 'Manage': 'eportfolio/manage.md'
  - 'Manage Advisors and Groups': 'eportfolio/manageadvisors.md'
  - 'Advisors': 'eportfolio/advisors.md'
  - 'Learners': 'eportfolio/learners.md'
  - 'Gradebook': 'eportfolio/gradebook.md'
- 'Annual Reports':
  - 'Getting Started': 'annualreports/index.md'
  - 'Faculty Annual Reports': 'annualreports/faculty.md'
  - 'Reporting Options': 'annualreports/reports.md'
- 'Regional Education':
  - 'Getting Started': 'regionaled/index.md'
  - 'Manage Regions': 'regionaled/regions.md'
  - 'Manage Apartments': 'regionaled/apartments.md'
  - 'Scheduling Learners': 'regionaled/schedules.md'
- 'User Tools':
  - 'My Bookmarks': 'usertools/bookmark.md'
  - 'People Search': 'usertools/peoplesearch.md'
  - 'Masking Identity': 'usertools/maskingid.md'
- 'Rich Text Content':
  - 'Using Rich Text Content Editor': 'richtexteditor/index.md'
